version: '4.3'

networks:
  app-networks:
    driver: bridge

services:
  app:
    build:
      context: ./trade-service
      dockerfile: Dockerfile
    container_name: anastasia
    networks:
      - app-networks
    depends_on:
      - mysql
      - smart
      - redis
    ports:
      - '8080:8080'

  smart:
    build:
      context: ./smart-service
      dockerfile: Dockerfile
    container_name: smart_service
    networks:
      - app-networks
    ports:
      - '9090:9090'

  telegram:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      - mysql
    networks:
      - app-networks
    ports:
      - '8081:8081'

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    networks:
      - app-networks
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trade_app
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - ./trade-service/resources/data:/var/lib/mysql/

  redis:
    image: redis:latest
    restart: always
    container_name: rediska
    networks:
      - app-networks
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
#      --requirepass 12345